/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Code.JpanelLoader;

/**
 *
 * @author Horizon
 */
public class inventory_full extends javax.swing.JPanel {

    /**
     * Creates new form inventory_full
     */
    
    JpanelLoader jpload = new JpanelLoader();
    
    public inventory_full() {
        initComponents();
        
        inventory inv = new inventory();
        jpload.jPanelLoader(inv_full, inv);
        
        stock_reports st_reports = new stock_reports();
        jpload.jPanelLoader(stock_reports, st_reports);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        inv_full = new javax.swing.JPanel();
        stock_reports = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout inv_fullLayout = new javax.swing.GroupLayout(inv_full);
        inv_full.setLayout(inv_fullLayout);
        inv_fullLayout.setHorizontalGroup(
            inv_fullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        inv_fullLayout.setVerticalGroup(
            inv_fullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Current Inventory", inv_full);

        javax.swing.GroupLayout stock_reportsLayout = new javax.swing.GroupLayout(stock_reports);
        stock_reports.setLayout(stock_reportsLayout);
        stock_reportsLayout.setHorizontalGroup(
            stock_reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stock_reportsLayout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1180, Short.MAX_VALUE))
        );
        stock_reportsLayout.setVerticalGroup(
            stock_reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stock_reportsLayout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 587, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Stock Reports", stock_reports);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel inv_full;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel stock_reports;
    // End of variables declaration//GEN-END:variables
}
