/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Code.JpanelLoader;

/**
 *
 * @author Horizon
 */
public class salary extends javax.swing.JPanel {

    /**
     * Creates new form inventory_full
     */
    
    JpanelLoader jpload = new JpanelLoader();
    
    public salary() {
        initComponents();
        
        emp_salary_monpay esm = new emp_salary_monpay();
        jpload.jPanelLoader(current_month, esm);
        
        role_salary rs = new role_salary();
        jpload.jPanelLoader(role_salary, rs);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        current_month = new javax.swing.JPanel();
        role_salary = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout current_monthLayout = new javax.swing.GroupLayout(current_month);
        current_month.setLayout(current_monthLayout);
        current_monthLayout.setHorizontalGroup(
            current_monthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        current_monthLayout.setVerticalGroup(
            current_monthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Upcoming Salary Payments", current_month);

        javax.swing.GroupLayout role_salaryLayout = new javax.swing.GroupLayout(role_salary);
        role_salary.setLayout(role_salaryLayout);
        role_salaryLayout.setHorizontalGroup(
            role_salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(role_salaryLayout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1180, Short.MAX_VALUE))
        );
        role_salaryLayout.setVerticalGroup(
            role_salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(role_salaryLayout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 587, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Salary Management", role_salary);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel current_month;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel role_salary;
    // End of variables declaration//GEN-END:variables
}
